services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=jannieplay_db'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=artu'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/data/postgresql
volumes:
  pgdata: